name: Temp Signing Test

on:
  workflow_dispatch:

jobs:
  test-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - run: ./gradlew :ota-core:signMavenPublication --stacktrace -x :ota-core:createStagingRepository
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: unused
          ORG_GRADLE_PROJECT_mavenCentralPassword: unused
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.TEST_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: 2BCD624B
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.TEST_SIGNING_KEY_PASSWORD }}
